#!/usr/bin/env python3
"""Run ACTUS rf2/scenarioSimulation in batches.

Inputs:
- contracts.json (from generate_contracts.py)
- scenario list (generated by build_risk_scenarios.py)

Outputs:
- raw JSON responses per scenario + behavior
"""
import argparse
import json
import math
import os
from pathlib import Path
import requests

ACTUS_URL = "http://localhost:8083"


def chunk(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--contracts", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--batch", type=int, default=50)
    ap.add_argument("--simulate-to", default="2025-01-01T00:00:00")
    ap.add_argument("--behavior", choices=["static", "rational"], required=True)
    ap.add_argument("--scenario-prefix", default="scn_")
    args = ap.parse_args()

    contracts = json.loads(Path(args.contracts).read_text(encoding="utf-8"))["contracts"]

    # Query scenarios from risk server is not exposed here; we build the list directly.
    irs = ["ir_up", "ir_down", "ir_vup", "ir_vdown"]
    eqs = ["eq_base", "eq_down", "eq_deep"]
    scenarios = [f"{args.scenario_prefix}{ir}_{eq}" for ir in irs for eq in eqs]

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    for scn in scenarios:
        scn_dir = outdir / scn / args.behavior
        scn_dir.mkdir(parents=True, exist_ok=True)

        for bi, batch in enumerate(chunk(contracts, args.batch), start=1):
            # Add behavior if requested
            if args.behavior == "rational":
                for c in batch:
                    c["prepaymentModels"] = ["ppm01"]
            else:
                for c in batch:
                    c.pop("prepaymentModels", None)

            payload = {
                "contracts": batch,
                "scenarioDescriptor": {"scenarioID": scn, "scenarioType": "scenario"},
                "simulateTo": args.simulate_to,
                "monitoringTimes": [],
            }
            r = requests.post(f"{ACTUS_URL}/rf2/scenarioSimulation", json=payload)
            r.raise_for_status()

            out_path = scn_dir / f"batch_{bi:03d}.json"
            out_path.write_text(r.text, encoding="utf-8")

            print(f"{scn} {args.behavior} batch {bi}")


if __name__ == "__main__":
    main()
